apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "livekit.fullname" . }}-token-service
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "livekit.token.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.tokenService.replicas }}
  selector:
    matchLabels:
      app: livekit-token-service
  template:
    metadata:
      labels:
        app: livekit-token-service
    spec:
      containers:
      - name: livekit-token-service
        image: "{{ .Values.tokenService.image.repository }}:{{ .Values.tokenService.image.tag }}"
        imagePullPolicy: {{ .Values.tokenService.image.pullPolicy }}
        ports:
        - name: http
          containerPort: {{ .Values.tokenService.service.targetPort }}
          protocol: TCP
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      terminationGracePeriodSeconds: 30



