apiVersion: v1
kind: Secret
metadata:
  name: tenantservice-secret
type: Opaque
data: 
  SPRING_DATASOURCE_USERNAME: {{ .Values.tenantService.springDatasourceUsername | b64enc | quote }} 
  SPRING_DATASOURCE_PASSWORD: {{ .Values.tenantService.springDatasourcePassword | b64enc | quote }} 
  SPRING_RABBITMQ_USERNAME: {{ .Values.tenantService.springRabbitmqUsername | b64enc | quote }}  
  SPRING_RABBITMQ_PASSWORD: {{ .Values.tenantService.springRabbitmqPassword | b64enc | quote }}  