apiVersion: apps/v1
kind: Deployment
metadata:
  name: consultingtypeservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consultingtypeservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: consultingtypeservice
    spec:
      containers:
        - name: consultingtypeservice
          image:  {{ .Values.consultingTypeService.imageName }}:{{ .Values.consultingTypeService.imageVersion }}          
          imagePullPolicy: Always
          env:
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: CONSULTINGTYPESERVICE_SPRING_DATASOURCE_PASSWORD
                  name: consultingtypeservice-secret
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: consultingtypeservice-configmap-env
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: CONSULTINGTYPESERVICE_SPRING_DATASOURCE_USERNAME
                  name: consultingtypeservice-secret
            - name: SPRING_LIQUIBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SPRING_LIQUIBASE_PASSWORD
                  name: consultingtypeservice-secret
            - name: SPRING_LIQUIBASE_USER
              valueFrom:
                secretKeyRef:
                  key: SPRING_LIQUIBASE_USER
                  name: consultingtypeservice-secret
            - name: CONSULTING_TYPES_JSON_PATH
              valueFrom:
                configMapKeyRef:
                  key: CONSULTING_TYPES_JSON_PATH
                  name: consultingtypeservice-configmap-env
            - name: CSRF_COOKIE_PROPERTY
              valueFrom:
                configMapKeyRef:
                  key: CSRF_COOKIE_PROPERTY
                  name: consultingtypeservice-configmap-env
            - name: CSRF_HEADER_PROPERTY
              valueFrom:
                configMapKeyRef:
                  key: CSRF_HEADER_PROPERTY
                  name: consultingtypeservice-configmap-env
            - name: TENANT_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  key: TENANT_SERVICE_API_URL
                  name: consultingtypeservice-configmap-env
            - name: MULTITENANCY_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: MULTITENANCY_ENABLED
                  name: consultingtypeservice-configmap-env
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  key: JAVA_OPTS
                  name: consultingtypeservice-configmap-env
            - name: APP_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: APP_BASE_URL
                  name: consultingtypeservice-configmap-env
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: SPRING_DATA_MONGODB_URI
                  name: consultingtypeservice-secret
            - name: KEYCLOAK_CORS
              valueFrom:
                 configMapKeyRef:
                  key: KEYCLOAK_CORS
                  name: consultingtypeservice-configmap-env
            - name: KEYCLOAK_PRINCIPAL_ATTRIBUTE
              valueFrom:
                 configMapKeyRef:
                  key: KEYCLOAK_PRINCIPAL_ATTRIBUTE
                  name: consultingtypeservice-configmap-env
            - name: KEYCLOAKSERVICE_ADMIN_CLIENTID
              valueFrom:
                 configMapKeyRef:
                  key: KEYCLOAKSERVICE_ADMIN_CLIENTID
                  name: consultingtypeservice-configmap-env
            - name: KEYCLOAKSERVICE_APP_CLIENTID
              valueFrom:
                 configMapKeyRef:
                  key: KEYCLOAKSERVICE_APP_CLIENTID
                  name: consultingtypeservice-configmap-env
            - name: KEYCLOAK_AUTH_SERVER_URL
              valueFrom:
                 configMapKeyRef:
                  key: KEYCLOAK_AUTH_SERVER_URL
                  name: consultingtypeservice-configmap-env
            - name: KEYCLOAK_REALM
              valueFrom:
                 configMapKeyRef:
                  key: KEYCLOAK_REALM
                  name: consultingtypeservice-configmap-env
            - name: KEYCLOAK_RESOURCE
              valueFrom:
                configMapKeyRef:
                 key: KEYCLOAK_RESOURCE
                 name: consultingtypeservice-configmap-env
          ports:
            - containerPort: 8080
          volumeMounts:
            - mountPath: /{{ .Values.consultingTypeService.consultingTypesJsonPath }}
              name: consulting-type-settings
      volumes:
        - name: consulting-type-settings
          configMap:
            name: consultingtypeservice-settings-configmap
