apiVersion: v1
kind: Secret
metadata:
  name: consultingtypeservice-secret
type: Opaque
data:
  {{- $mongourl := printf "mongodb://%s:%s@mongodb.%s:27017/consulting_types?retryWrites=false" .Values.global.secrets.consultingTypeMongoUser .Values.global.secrets.consultingTypeMongoPass .Release.Namespace }}
  SPRING_DATA_MONGODB_URI: {{ $mongourl | b64enc | quote }}
  SPRING_LIQUIBASE_USER: {{ .Values.global.secrets.liquibaseUser | b64enc | quote }}
  SPRING_LIQUIBASE_PASSWORD: {{ .Values.global.secrets.liquibasePassword | b64enc | quote }}
  CONSULTINGTYPESERVICE_SPRING_DATASOURCE_USERNAME: {{ .Values.global.secrets.consultingTypeServiceDbUsername | b64enc | quote }}
  CONSULTINGTYPESERVICE_SPRING_DATASOURCE_PASSWORD: {{ .Values.global.secrets.consultingTypeServiceDbPassword | b64enc | quote }}
