apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
    {{- if .Values.global.enableCors }}
    nginx.ingress.kubernetes.io/enable-cors: "{{ .Values.global.enableCors }}"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.global.corsAllowOrigin }}"
    nginx.ingress.kubernetes.io/cors-allow-headers: "{{ .Values.global.corsAllowHeaders }}"
    {{- end }}
  name: consultingtypeservice
spec:
  ingressClassName: nginx
  rules:
  {{- if .Values.global.multitenancyEnabled }}
    - host: "*.{{ .Values.global.domainName }}"
  {{- else }}
    - host: {{ .Values.global.domainName }}
  {{- end }}
      http:
        paths:
          - backend:
              service:
                name: consultingtypeservice
                port:
                  number: 8080
            path: /service/(consultingtypes|consultingtypeadmin|topic)(.*)
            pathType: Prefix
