keycloakImageName: "quay.io/keycloak/keycloak"
keycloakVersion: "20.0.5"

dbVendor: "MARIADB"
dbDatabase: "keycloak"

# Logging
# Supported log levels are ALL, DEBUG, ERROR, FATAL, INFO, OFF, TRACE and WARN.
keycloakLogLevel: "WARN"
rootLogLevel: "WARN" 
 