apiVersion: v1
kind: Service
metadata:
  name: {{ include "signoz.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "signoz.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: http
  - port: {{ .Values.service.internalPort }}
    targetPort: {{ .Values.service.internalPort }}
    protocol: TCP
    name: http-internal
  - port: {{ .Values.service.opampPort }}
    targetPort: {{ .Values.service.opampPort }}
    protocol: TCP
    name: opamp-internal
  - port: 4317
    targetPort: 4317
    protocol: TCP
    name: otel-grpc
  - port: 4318
    targetPort: 4318
    protocol: TCP
    name: otel-http
  selector:
    app.kubernetes.io/component: signoz
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: {{ include "signoz.name" . }}
  clusterIP: None  # Headless service for StatefulSet

