apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
type: Opaque
data:
  REDIS_DEFAULT_PASS: {{ .Values.global.secrets.redisdefaultPass | b64enc | quote }}
  HTTP_USER: {{ .Values.user }}
  HTTP_PASSWORD: {{ .Values.global.secrets.redisdefaultPass  | b64enc | quote }}
  PASSWORD:  {{ .Values.global.secrets.redisdefaultPass  | b64enc | quote }}

