apiVersion: v1
kind: Service
metadata:
  name: {{ include "mariadb.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "mariadb.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
    name: mysql
  selector:
    app: mariadb
  clusterIP: None  # Headless service for StatefulSet



