apiVersion: v1
kind: Secret
metadata:
  name: matrix-postgres-secret
  namespace: caritas
type: Opaque
data:

  POSTGRES_DB: {{ .Values.postgres.postgresDB | b64enc | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.postgresPassword | b64enc | quote }}
  POSTGRES_USER: {{ .Values.postgres.postgresUser | b64enc | quote }} 