apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-synapse-data
  namespace: caritas
  labels:
    app: matrix-synapse
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: block-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-postgres-pvc
  namespace: caritas
  labels:
    app: matrix-postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: block-storage
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: matrix-postgres-backup-pvc
  namespace: caritas
  labels:
    app: matrix-postgres
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: block-storage

