apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret-env
type: Opaque
data:
  DB_USER: {{ .Values.global.secrets.keycloakDbUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.global.secrets.keycloakDbPassword | b64enc | quote }} 
  KEYCLOAK_ADMIN: {{ .Values.global.secrets.keycloakAdminUsername | b64enc | quote }} 
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.global.secrets.keycloakAdminPassword | b64enc | quote }} 

  
  