apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-theme-pv
  labels:
    io.kompose.service: keycloak-theme
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/keycloak-theme   # Change this path to your actual storage directory
  claimRef:
    name: keycloak-theme
    namespace: default    # change if your PVC is in another namespace