apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret-env
type: Opaque
data:
  DB_USER: {{ .Values.global.secrets.keycloakDbUsername | b64enc | quote }}
  DB_PASSWORD: {{ .Values.global.secrets.keycloakDbPassword | b64enc | quote }}