apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret-env
  labels:
    app: app
type: Opaque
data:
  DB_USER: {{ .Values.dbUser | b64enc | quote }}
  DB_PASSWORD: {{ .Values.dbPassword | b64enc | quote }}