apiVersion: v1
data:
  binaryData:
    {{ .Files.Get "resources/dump.tar" | b64enc | nindent 4 }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: mongo-dump-{{ .Release.Name }}-configmap
  name: mongodb-dump-{{ .Release.Name }}-configmap
