apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: {{ .Values.mongoInitDbRootUsername | b64enc | quote }}
  MONGO_INITDB_ROOT_PASSWORD: {{ .Values.mongoInitDbRootPassword | b64enc | quote }}
  MONGO_NOSQLCLIENT_USER: {{ .Values.noSqlClientMongoUsername | b64enc | quote }}
  MONGO_NOSQLCLIENT_PASSWORD: {{ .Values.noSqlClientMongoPassword | b64enc | quote }}
  MONGO_ROCKETCHAT_USER: {{ .Values.rocketchatMongoUsername | b64enc | quote }}
  MONGO_ROCKETCHAT_PASSWORD: {{ .Values.rocketchatMongoPassword | b64enc | quote }}
  MONGO_OPLOG_USER: {{ .Values.oplogMongoUsername | b64enc | quote }}
  MONGO_OPLOG_PASSWORD: {{ .Values.oplogMongoPassword | b64enc | quote }}
  MONGO_STATISTICS_USER: {{ .Values.statisticsMongoUser | b64enc | quote }}
  MONGO_STATISTICS_PASSWORD: {{ .Values.statisticsMongoPass | b64enc | quote }}
  MONGO_CONSULTING_TYPES_USER: {{ .Values.global.secrets.consultingTypeMongoUser | b64enc | quote }}
  MONGO_CONSULTING_TYPES_PASSWORD: {{ .Values.global.secrets.consultingTypeMongoPass | b64enc | quote }}
