{{- if .Values.global.initializeDummyData }}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-nosqlclient-user
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    spec:
      initContainers:
        - name: wait-for-mongo-admin
          image: {{ .Values.mongoImageName }}:{{ .Values.mongoVersion }}
          args:
            - /bin/sh
            - -c
            - >
              set -x;
              while [ ! -f /init/data/mongo-database-initialized.lock ]; do
                sleep 15;
              done
          volumeMounts:
            - mountPath: /init/data
              name: plattform-init-data
      containers:
        - name: create-mongo-nosqlclient
          image: {{ .Values.mongoImageName }}:{{ .Values.mongoVersion }}
          env:
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: mongodb-secret-{{ .Release.Name }}-env
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: mongodb-secret-{{ .Release.Name }}-env
            - name: MONGODB_NOSQLCLIENT_USER
              valueFrom:
                secretKeyRef:
                  key: MONGO_NOSQLCLIENT_USER
                  name: mongodb-secret-{{ .Release.Name }}-env
            - name: MONGODB_NOSQLCLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_NOSQLCLIENT_PASSWORD
                  name: mongodb-secret-{{ .Release.Name }}-env
          command:
            - /bin/bash
            - -c
            - >
              mongosh "mongodb://$MONGODB_USERNAME:$MONGODB_PASSWORD@mongodb.{{ .Release.Namespace }}:27017"
              --eval
              "db = db.getSiblingDB('nosqlclient');
              db.createUser({
                user: '$MONGODB_NOSQLCLIENT_USER',
                pwd: '$MONGODB_NOSQLCLIENT_PASSWORD',
                roles: [{ role: 'readWrite', db: 'nosqlclient' }]});"
      restartPolicy: Never
      volumes:
        - name: plattform-init-data
          persistentVolumeClaim:
            claimName: plattform-initialization-data
  backoffLimit: 50
{{- end }}