{{- if .Values.global.initializeDummyData }}
apiVersion: batch/v1
kind: Job
metadata:
  name: create-mongo-users
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  template:
    spec:
      restartPolicy: Never
      initContainers:
        - name: wait-for-mongo-ready
          image: busybox:1.36 # Oder ein Image mit netcat/nc
          command: ['sh', '-c', 'until nc -z mongodb.{{ .Release.Namespace }} 27017; do echo waiting for mongodb; sleep 2; done']
      containers:
        - name: create-mongo-users
          image: {{ .Values.imageName }}:{{ .Values.imageVersion }}
          env:
            - name: MONGODB_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_USERNAME
                  name: mongodb-secret
            - name: MONGODB_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_INITDB_ROOT_PASSWORD
                  name: mongodb-secret
            - name: MONGO_NOSQLCLIENT_USER
              valueFrom:
                secretKeyRef:
                  key: MONGO_NOSQLCLIENT_USER
                  name: mongodb-secret
            - name: MONGO_NOSQLCLIENT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_NOSQLCLIENT_PASSWORD
                  name: mongodb-secret
            - name: MONGO_STATISTICS_USER
              valueFrom:
                secretKeyRef:
                  key: MONGO_STATISTICS_USER
                  name: mongodb-secret
            - name: MONGO_STATISTICS_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_STATISTICS_PASSWORD
                  name: mongodb-secret
            - name: MONGO_CONSULTING_TYPES_USER
              valueFrom:
                secretKeyRef:
                  key: MONGO_CONSULTING_TYPES_USER
                  name: mongodb-secret
            - name: MONGO_CONSULTING_TYPES_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MONGO_CONSULTING_TYPES_PASSWORD
                  name: mongodb-secret
          command:
            - /bin/bash
            - -c
            - >
              set -e;
              echo "Creating user: nosqlclient";
              mongosh "mongodb://$MONGODB_USERNAME:$MONGODB_PASSWORD@mongodb.{{ .Release.Namespace }}:27017/?replicaSet=rs0" --eval "db=db.getSiblingDB('nosqlclient'); db.createUser({ user: '$MONGO_NOSQLCLIENT_USER', pwd: '$MONGO_NOSQLCLIENT_PASSWORD', roles: [{ role: 'readWrite', db: 'nosqlclient' }]});" &&
              echo "Creating user: statistics";
              mongosh "mongodb://$MONGODB_USERNAME:$MONGODB_PASSWORD@mongodb.{{ .Release.Namespace }}:27017/?replicaSet=rs0" --eval "db=db.getSiblingDB('statistics'); db.createUser({ user: '$MONGO_STATISTICS_USER', pwd: '$MONGO_STATISTICS_PASSWORD', roles: [{ role: 'readWrite', db: 'statistics' }]});" &&
              echo "Creating user: consulting_types";
              mongosh "mongodb://$MONGODB_USERNAME:$MONGODB_PASSWORD@mongodb.{{ .Release.Namespace }}:27017/?replicaSet=rs0" --eval "db=db.getSiblingDB('consulting_types'); db.createUser({ user: '$MONGO_CONSULTING_TYPES_USER', pwd: '$MONGO_CONSULTING_TYPES_PASSWORD', roles: [{ role: 'readWrite', db: 'consulting_types' }]});"
  backoffLimit: 1
{{- end }}
