apiVersion: v1
kind: Secret
metadata:
  name: agencyservice-secret
type: Opaque
data:
  SPRING_LIQUIBASE_USER: {{ .Values.global.secrets.liquibaseUser | b64enc | quote }}
  SPRING_LIQUIBASE_PASSWORD: {{ .Values.global.secrets.liquibasePassword | b64enc | quote }}
  AGENCYSERVICE_SPRING_DATASOURCE_USERNAME: {{ .Values.global.secrets.agencyServiceDbUsername | b64enc | quote }}
  AGENCYSERVICE_SPRING_DATASOURCE_PASSWORD: {{ .Values.global.secrets.agencyServiceDbPassword | b64enc | quote }}
  MATRIX_ADMIN_USERNAME: {{ .Values.matrix.matrixAdminUsername | b64enc | quote }}   
  MATRIX_ADMIN_PASSWORD: {{ .Values.matrix.matrixAdminPassword | b64enc | quote }}   
  MATRIX_REGISTRATION_SHARED_SECRET: {{.Values.global.secrets.matrixRegistrationSharedSecret | b64enc | quote }}     

