apiVersion: apps/v1
kind: Deployment
metadata:
  name: agencyservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: agencyservice
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: agencyservice
    spec:
      containers:
        - name: agencyservice
          image: {{ .Values.agencyService.imageName }}:{{ .Values.agencyService.imageVersion }}          
          imagePullPolicy: Always
          env:
            - name: CSRF_COOKIE_PROPERTY
              valueFrom:
                configMapKeyRef:
                  key: CSRF_COOKIE_PROPERTY
                  name: agencyservice-configmap-env
            - name: CSRF_HEADER_PROPERTY
              valueFrom:
                configMapKeyRef:
                  key: CSRF_HEADER_PROPERTY
                  name: agencyservice-configmap-env
            - name: KEYCLOAK_CORS
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_CORS
                  name: agencyservice-configmap-env
            - name: KEYCLOAK_PRINCIPAL_ATTRIBUTE
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_PRINCIPAL_ATTRIBUTE
                  name: agencyservice-configmap-env
            - name: KEYCLOAKSERVICE_ADMIN_CLIENTID
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAKSERVICE_ADMIN_CLIENTID
                  name: agencyservice-configmap-env
            - name: KEYCLOAKSERVICE_APP_CLIENTID
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAKSERVICE_APP_CLIENTID
                  name: agencyservice-configmap-env
            - name: KEYCLOAK_AUTH_SERVER_URL
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_AUTH_SERVER_URL
                  name: agencyservice-configmap-env
            - name: KEYCLOAK_REALM
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_REALM
                  name: agencyservice-configmap-env
            - name: KEYCLOAK_RESOURCE
              valueFrom:
                configMapKeyRef:
                  key: KEYCLOAK_RESOURCE
                  name: agencyservice-configmap-env
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: AGENCYSERVICE_SPRING_DATASOURCE_PASSWORD
                  name: agencyservice-secret
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATASOURCE_URL
                  name: agencyservice-configmap-env
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: AGENCYSERVICE_SPRING_DATASOURCE_USERNAME
                  name: agencyservice-secret
            - name: SPRING_LIQUIBASE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: SPRING_LIQUIBASE_PASSWORD
                  name: agencyservice-secret
            - name: SPRING_LIQUIBASE_USER
              valueFrom:
                secretKeyRef:
                  key: SPRING_LIQUIBASE_USER
                  name: agencyservice-secret
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  key: SPRING_PROFILES_ACTIVE
                  name: agencyservice-configmap-env                  
            - name: TOPIC_ENRICHMENT_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: TOPIC_ENRICHMENT_ENABLED
                  name: agencyservice-configmap-env      
            - name: CONSULTING_TYPE_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  key: CONSULTING_TYPE_SERVICE_API_URL
                  name: agencyservice-configmap-env
            - name: TENANT_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  key: TENANT_SERVICE_API_URL
                  name: agencyservice-configmap-env
            - name: MULTITENANCY_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: MULTITENANCY_ENABLED
                  name: agencyservice-configmap-env
            - name: FEATURE_TOPICS_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: FEATURE_TOPICS_ENABLED
                  name: agencyservice-configmap-env
            - name: FEATURE_DEMOGRAPHICS_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: FEATURE_DEMOGRAPHICS_ENABLED
                  name: agencyservice-configmap-env
            - name: JAVA_OPTS
              valueFrom:
                configMapKeyRef:
                  key: JAVA_OPTS
                  name: agencyservice-configmap-env
            - name: APP_BASE_URL
              valueFrom:
                configMapKeyRef:
                  key: APP_BASE_URL
                  name: agencyservice-configmap-env
            - name: USER_ADMIN_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  key: USER_ADMIN_SERVICE_API_URL
                  name: agencyservice-configmap-env
            - name: FEATURE_APPOINTMENT_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: FEATURE_APPOINTMENT_ENABLED
                  name: agencyservice-configmap-env
            - name: APPOINTMENT_SERVICE_API_URL
              valueFrom:
                configMapKeyRef:
                  key: APPOINTMENT_SERVICE_API_URL
                  name: agencyservice-configmap-env
            - name: FEATURE_MULTITENANCY_WITH_SINGLE_DOMAIN_ENABLED
              valueFrom:
                configMapKeyRef:
                  key: FEATURE_MULTITENANCY_WITH_SINGLE_DOMAIN_ENABLED
                  name: agencyservice-configmap-env
            - name: AGENCY_DELETEWORKFLOW_CRON
              valueFrom:
                configMapKeyRef:
                  key: AGENCY_DELETEWORKFLOW_CRON
                  name: agencyservice-configmap-env
            - name: MATRIX_API_URL
              valueFrom:
                configMapKeyRef:
                  key: MATRIX_API_URL
                  name: agencyservice-configmap-env
            - name: MATRIX_SERVER_NAME
              valueFrom:
                configMapKeyRef:
                  key: MATRIX_SERVER_NAME
                  name: agencyservice-configmap-env
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI
                  name: agencyservice-configmap-env
            - name: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI
                  name: agencyservice-configmap-env       
            - name: MATRIX_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: MATRIX_ADMIN_PASSWORD
                  name: agencyservice-secret                
            - name: MATRIX_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: MATRIX_ADMIN_USERNAME
                  name: agencyservice-secret                
            - name: MATRIX_REGISTRATION_SHARED_SECRET
              valueFrom:
                secretKeyRef:
                  key: MATRIX_REGISTRATION_SHARED_SECRET
                  name: agencyservice-secret                
            - name: SPRING_DATA_MONGODB_URI
              valueFrom:
                configMapKeyRef:
                  key: SPRING_DATA_MONGODB_URI
                  name: agencyservice-configmap-env   
          ports:
            - containerPort: 8080
