apiVersion: v1
kind: Secret
metadata:
  name: userservice-secret
type: Opaque
data:
  SERVICE_ENCRYPTION_APPKEY: {{ .Values.userService.serviceEncryptionAppkey | b64enc | quote }}
  SPRING_LIQUIBASE_USER: {{ .Values.global.secrets.liquibaseUser | b64enc | quote }}
  SPRING_LIQUIBASE_PASSWORD: {{ .Values.global.secrets.liquibasePassword | b64enc | quote }}
  SPRING_RABBITMQ_USERNAME: {{ .Values.global.secrets.rabbitmqUsername | b64enc | quote }}
  SPRING_RABBITMQ_PASSWORD: {{ .Values.global.secrets.rabbitmqPassword | b64enc | quote }}
  USERSERVICE_SPRING_DATASOURCE_USERNAME: {{ .Values.global.secrets.userServiceDbUsername | b64enc | quote }}
  USERSERVICE_SPRING_DATASOURCE_PASSWORD: {{ .Values.global.secrets.userServiceDbPassword | b64enc | quote }}
  KEYCLOAK_CONFIG_ADMIN_USERNAME: {{ .Values.userService.keycloakAdminUsername | b64enc | quote }}
  KEYCLOAK_CONFIG_ADMIN_PASSWORD: {{ .Values.userService.keycloakAdminPassword | b64enc | quote }}
  KEYCLOAKSERVICE_TECHNICAL_USERNAME: {{ .Values.userService.keycloakTechnicalUsername | b64enc | quote }}
  KEYCLOAKSERVICE_TECHNICAL_PASSWORD: {{ .Values.userService.keycloakTechnicalPassword | b64enc | quote }} 
  ROCKET_SYSTEMUSER_USERNAME: {{ .Values.userService.rocketSystemuserUsername | b64enc | quote }}
  ROCKET_SYSTEMUSER_PASSWORD: {{ .Values.userService.rocketSystemuserPassword | b64enc | quote }}
  ROCKET_TECHNICAL_USERNAME: {{ .Values.userService.rocketTechnicalUsername | b64enc | quote }}
  ROCKET_TECHNICAL_PASSWORD: {{ .Values.userService.rocketTechnicalPassword | b64enc | quote }}
  MATRIX_REGISTRATION_SHARED_SECRET: {{ .Values.matrix.matrixRegistrationSharedSecret | b64enc | quote }}   