apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1$2
    {{- if .Values.enableCors }}
    nginx.ingress.kubernetes.io/enable-cors: "{{ .Values.enableCors }}"
    nginx.ingress.kubernetes.io/cors-allow-origin: "{{ .Values.corsAllowOrigin }}"
    nginx.ingress.kubernetes.io/cors-allow-headers: "{{ .Values.corsAllowHeaders }}"
    {{- end }}
  name: userservice
  namespace: {{ .Release.Namespace }}
spec:
  ingressClassName: nginx
  rules:
  {{- if .Values.global.multitenancyEnabled }}
    - host: "*.{{ .Values.global.domainName }}"
  {{- else }}
    - host: {{ .Values.global.domainName }}
  {{- end }}
      http:
        paths:
          - backend:
              service:
                name: userservice
                port:
                  number: 8080
            path: /service/(users|conversations|liveproxy|useradmin|appointments)(.*)
            pathType: Prefix
