apiVersion: v1
kind: Secret
metadata:
  name: userservice-secret-{{ .Release.Name }}-env
  labels:
    app: app
type: Opaque
data: 
  USERSERVICE_SPRING_DATASOURCE_USERNAME: {{ .Values.global.userServiceSpringDatasourceUsername | b64enc | quote }}
  USERSERVICE_SPRING_DATASOURCE_PASSWORD: {{ .Values.global.userServiceSpringDatasourcePassword | b64enc | quote }}
  KEYCLOAK_CONFIG_ADMIN_USERNAME: {{ .Values.userService.keycloakAdminUsername | b64enc | quote }}
  KEYCLOAK_CONFIG_ADMIN_PASSWORD: {{ .Values.userService.keycloakAdminPassword | b64enc | quote }}
  KEYCLOAKSERVICE_TECHNICAL_USERNAME: {{ .Values.userService.keycloakTechnicalUsername | b64enc | quote }}
  KEYCLOAKSERVICE_TECHNICAL_PASSWORD: {{ .Values.userService.keycloakTechnicalPassword | b64enc | quote }} 
