apiVersion: v1
kind: Service
metadata:
  name: {{ include "otel-collector.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "otel-collector.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: otlpgrpc
    port: {{ .Values.service.ports.otlpGrpc }}
    targetPort: otlpgrpc
    protocol: TCP
  - name: otlphttp
    port: {{ .Values.service.ports.otlpHttp }}
    targetPort: otlphttp
    protocol: TCP
  - name: metrics
    port: {{ .Values.service.ports.metrics }}
    targetPort: metrics
    protocol: TCP
  selector:
    app: otel-collector

