apiVersion: v1
kind: Secret
metadata:
  name: {{ include "agencyservice.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "agencyservice.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database Credentials
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | quote }}
  
  # Keycloak Admin Credentials
  KEYCLOAK_CONFIG_ADMIN_USERNAME: {{ .Values.keycloak.config.adminUsername | quote }}
  KEYCLOAK_CONFIG_ADMIN_PASSWORD: {{ .Values.keycloak.config.adminPassword | quote }}
  
  # Matrix Credentials
  MATRIX_REGISTRATION_SHARED_SECRET: {{ .Values.matrix.registrationSharedSecret | quote }}
  MATRIX_ADMIN_USERNAME: {{ .Values.matrix.adminUsername | quote }}
  MATRIX_ADMIN_PASSWORD: {{ .Values.matrix.adminPassword | quote }}
  
  # Rocket.Chat Credentials
  ROCKET_TECHNICAL_USERNAME: {{ .Values.rocketchat.technical.username | quote }}
  ROCKET_TECHNICAL_PASSWORD: {{ .Values.rocketchat.technical.password | quote }}
