apiVersion: v1
kind: Secret
metadata:
  name: {{ include "consultingtypeservice.fullname" . }}-secrets
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "consultingtypeservice.labels" . | nindent 4 }}
type: Opaque
stringData:
  # Database Credentials
  SPRING_DATASOURCE_USERNAME: {{ .Values.database.username | quote }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.database.password | quote }}
  
  # Keycloak Admin Credentials
  KEYCLOAK_CONFIG_ADMIN_USERNAME: "technical"
  KEYCLOAK_CONFIG_ADMIN_PASSWORD: "technical"


