apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rabbitmq.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "rabbitmq.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: rabbitmq
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: RABBITMQ_DEFAULT_USER
          {{- if .Values.rabbitmq.secret.name }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.rabbitmq.secret.name }}
              key: {{ .Values.rabbitmq.secret.keys.user }}
          {{- else if .Values.rabbitmq.defaultUser }}
          value: {{ .Values.rabbitmq.defaultUser | quote }}
          {{- end }}
        - name: RABBITMQ_DEFAULT_PASS
          {{- if .Values.rabbitmq.secret.name }}
          valueFrom:
            secretKeyRef:
              name: {{ .Values.rabbitmq.secret.name }}
              key: {{ .Values.rabbitmq.secret.keys.pass }}
          {{- else if .Values.rabbitmq.defaultPass }}
          value: {{ .Values.rabbitmq.defaultPass | quote }}
          {{- end }}
        ports:
        - name: amqp
          containerPort: {{ .Values.service.ports.amqp }}
          protocol: TCP
        - name: management
          containerPort: {{ .Values.service.ports.management }}
          protocol: TCP
        {{- if .Values.resources }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
        {{- end }}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      terminationGracePeriodSeconds: 30



